export enum ErrorCode {
  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // Auth
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  UNAUTHORIZED_ROLE = 'UNAUTHORIZED_ROLE',

  // Company
  CNPJ_INVALID = 'CNPJ_INVALID',
  CNPJ_ALREADY_EXISTS = 'CNPJ_ALREADY_EXISTS',
  COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND',
  COMPANY_SUSPENDED = 'COMPANY_SUSPENDED',
  COMPANY_CLOSED = 'COMPANY_CLOSED',

  // Account
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  DAILY_LIMIT_EXCEEDED = 'DAILY_LIMIT_EXCEEDED',

  // Pix
  PIX_KEY_NOT_FOUND = 'PIX_KEY_NOT_FOUND',
  PIX_KEY_ALREADY_EXISTS = 'PIX_KEY_ALREADY_EXISTS',
  PIX_RATE_LIMIT = 'PIX_RATE_LIMIT',
  PIX_TRANSFER_FAILED = 'PIX_TRANSFER_FAILED',
  PIX_MAX_KEYS = 'PIX_MAX_KEYS',

  // Invoice
  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',
  INVOICE_ALREADY_PAID = 'INVOICE_ALREADY_PAID',
  INVOICE_ALREADY_CANCELLED = 'INVOICE_ALREADY_CANCELLED',
  INVOICE_CANNOT_CANCEL = 'INVOICE_CANNOT_CANCEL',

  // Card
  CARD_NOT_FOUND = 'CARD_NOT_FOUND',
  CARD_BLOCKED = 'CARD_BLOCKED',
  CARD_LIMIT_EXCEEDED = 'CARD_LIMIT_EXCEEDED',

  // Team
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  MEMBER_ALREADY_EXISTS = 'MEMBER_ALREADY_EXISTS',
  CANNOT_REMOVE_OWNER = 'CANNOT_REMOVE_OWNER',

  // Notification
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
}
